eureka:
  client:
    serviceUrl:
      defaultZone: http://test1:1111/eureka/
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          search-paths: respo
server:
  port: 5555
